target 'MemoryTunes' do
  use_frameworks!

  pod 'ReSwift', '~> 4.0.0'
  # pod 'ReSwiftRecorder', '~> 0.4.0'
  pod 'ReSwiftRouter', '~> 0.6.0'
  
  pod 'Kingfisher', '~> 3.3.3'
  
  target 'MemoryTunesTests' do
    inherit! :search_paths

  end
end
