target 'MemoryTunes' do
  use_frameworks!

  pod 'RxSwift', '~> 3.6.1'
  pod 'ReactiveReSwift', '~>3.0.6'
  
  pod 'Kingfisher', '~> 3.3.3'
  
  target 'MemoryTunesTests' do
    inherit! :search_paths

  end
end
